# Streamlit Secrets Configuration
# This file should be placed in .streamlit/secrets.toml

# Your Serper API Key
SERPER_API_KEY = "your-serper-api-key-here"

# You can add other secrets here as needed
# DATABASE_URL = "postgresql://user:password@host:port/dbname"
# OTHER_API_KEY = "another-api-key"
